baseURL = 'https://vellankiindeevar.github.io/'
languageCode = 'en-us'
title = 'Vellankiindeevar'
theme='etch'

[params]
  description = "Your site description"
  copyright = "Copyright © 2022 Vellankiindeevar"
  dark = "auto"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 20
